version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: typo3
        MYSQL_DATABASE: typo3
        MYSQL_USER: typo3
        MYSQL_PASSWORD: typo3
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
    ports:
      - '33061:3306'
  solr:
    image: typo3solr/ext-solr
    ports:
      - '8999:8983'
  web:
    image: webdevops/php-apache:ubuntu-16.04
    environment:
        WEB_DOCUMENT_ROOT: /app/web/
        TYPO3_CONTEXT: Development
    ports:
      - '8900:80'
    links:
      - solr
      - mysql
    volumes:
      - .:/app/
