version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: typo3
        MYSQL_DATABASE: typo3
        MYSQL_USER: typo3
        MYSQL_PASSWORD: typo3
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
    ports:
      - '33060:3306'
